server:
    # https://nlnetlabs.nl/documentation/unbound/unbound.conf/
    # https://wiki.debian-fr.xyz/Utiliser_Unbound_avec_DNSSEC
    verbosity: 0
    chroot: ""
    interface: 0.0.0.0
    access-control: 0.0.0.0/0 allow
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    minimal-responses: yes

    hide-identity: yes
    hide-version: yes

    cache-min-ttl: 0
    cache-max-ttl: 86400

    pidfile:/tmp/unbound.pid
    do-daemonize: no

    use-syslog: yes
    log-queries: no
    log-replies: no

    val-log-level: 2
    val-permissive-mode: yes
    module-config: "validator python iterator"

python:
    python-script: "/padsi-dns-bin/unbound-module.py"
