build:
	make -C data-access-guard
	make -C fw-logger
	make -C init
	make -C padsi-do
	make -C usb-monitor
	make -C vm-agent
	make -C wayland-proxy
	make -C web-infra

clean:
	make -C data-access-guard clean
	make -C fw-logger clean
	make -C init clean
	make -C padsi clean
	make -C padsi-do clean
	make -C usb-monitor clean
	make -C vm-agent clean
	make -C wayland-proxy clean
	make -C web-infra clean
